last_name = input ("What is your last name? ")
first_name = input ("What is your first name? ")
job_title = input ("What si your job title? ")
id_number = input ("What is your ID Number? ")
email = input ("What is your email? ")
phone_number = input ("What is your phone number? ")

print()
print (" The ID Card is: ")
print ("-------------------------------------")
print (""+last_name.upper()+", "+first_name.capitalize()+"")
print (""+job_title.title()+"")
print ("ID: "+id_number+"")
print()
print (""+email.lower()+"")
print (""+phone_number+"")
print ("-------------------------------------")
